### ISSUE TITLE
Cool project bull nill pointer deref

### ISSUE THREAD

**Issue by supergeoff** [TheAxeDude/ZiniGo#1]
Hello,
It's a nice little project and I'd like to use it.
So far there is a nil pointer deref in the GetLibrary function,
I believe it has to do with the read all that does not read anything due to a bad response from the Zinio API but it is just a guess...

I'm not good at Go (or at programming for that matter) either but maybe it would be nice to get the API urls out of the code because they tend to evolve quite a lot ?

Anyway I encourage you to keep working on this because I'm sure there is plenty of people that would find it useful.

Have a nice day.

**Comment by TheAxeDude** [comment]
Thanks for the feedback!

I have experienced the issue myself, definitely related to the API URL. I will externalise it, along with finding a way to figure out which endpoint they are currently using, and let you know!

**Comment by TheAxeDude** [comment]
Hi @supergeoff 

I've pushed a commit and created a new release that partially resolves the issue, by allowing an endpoint to be passed in. I still need to do some investigation to see if the URL can be scraped from Zinio itself.

**Comment by supergeoff** [comment]
Hello,
Thank you @TheAxeDude I feel thats a better way to go for things that tends to change like APIs. And you idea to suggests a base url but let the user override it is the best of both world.
It does work now and it properly retreive the list of magazines. 
The chrome rendering is only blank files though.
For me it probably has to do with the fact that I'm on windows.

I've not checked the code in details but do you query the html directly from Zinio ? Or do you load from use some kind of local storage from the Zinio reader app where it caches the library?

I like your idea of using google chrome because the reader app is just some kind of webkit view...

Although if the APIs are changing a lot, another options would be to automate the Zinio reader to spit out the pdf files through its print option...

Best regards;

**Comment by TheAxeDude** [comment]
HI @supergeoff 

I'm glad the data is coming through (thats a start). I am also running Windows, so we should be able to get you up and running!

The way the code works, is that each page is stored as an SVG on a CDN (this page is unprotected, oddly enough). The API returns a list of the pages, and the URL to their SVG. I inject the SVG into an html template, and use chrome to print-to-pdf that page.

Can you confirm that the "template.html" file (see the releases) is in the same directory as your executable, and that you're executing it from that same directory?

**Comment by supergeoff** [comment]
Right the template.html...
Oups my bad on this one I did not see the template and it does work perfectly.
Very nice job sir.

Thank you very much!

**Comment by TheAxeDude** [comment]
Only a pleasure!

I think I will make a change to use a "default" template within the code, and added it as an override option.
