### ISSUE TITLE
app crashes after 306 issues

### ISSUE THREAD

**Issue by BlackB846** [TheAxeDude/ZiniGo#11]
Hi

I have a relative large library and your last improvement to download more than 10 issues really made a difference. Never the less after 306 issues, the app crashes with the following message (windows version)

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x7b6a1f]

goroutine 1 [running]:
main.fileExists(0xc0014f45b0, 0x69, 0x6)
        C:/projects/ZiniGo/Grabazine.go:308 +0x9f
main.main()
        C:/projects/ZiniGo/Grabazine.go:106 +0xa4d

I now have 306 files in my issue folder and if I restart the app, it will list all of them as already downloaded and then crash with above message.

Thanks

**Comment by TheAxeDude** [comment]
Thats weird! I'll add some extra logging so we can try see why it might be failing there. Possibly some weird characters in the issue title, or something.

**Comment by TheAxeDude** [comment]
Hi, I've added some extra output for this case - perhaps we can see something weird with the issue being downloaded.

**Comment by BlackB846** [comment]
Checking if issue exists: C:\Users\aburc\Downloads\zinio/issue/Australian Penthouse Black Label -       December 2017 _ January 2018.pdf
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x7e098f]

goroutine 1 [running]:
main.fileExists(0xc000135f80, 0x69, 0xc0003373c8)
        C:/projects/ZiniGo/Grabazine.go:306 +0x9f
main.main()
        C:/projects/ZiniGo/Grabazine.go:104 +0xb03

**Comment by BlackB846** [comment]
Looking at the error message here and comparing it to my screen I could imagine a <tab> character in the name. That's obviously not visible here in the post.

**Comment by TheAxeDude** [comment]
Working a fix that now :)

**Comment by TheAxeDude** [comment]
Please give it bash!

**Comment by BlackB846** [comment]
The issue that caused the problem is downloading now. Thanks for your help.

**Comment by TheAxeDude** [comment]
Awesome, feel free to open another issue if you have more issues.
