### ISSUE TITLE
Chrome isn't opening.

### ISSUE THREAD

**Issue by matheusmaus** [TheAxeDude/ZiniGo#12]
Error message:

> cmd.Run() failed with exec: "google-chrome": executable file not found in %PATH%

I tried in the both ways, using the config.json and via the path [-c=], both result the same error. 

What can be my mistake here?

**Comment by TheAxeDude** [comment]
Hi @matheusmaus

Apologies I only saw this issue today. 

Are you running on windows/linux? Off the top of my head, there might be spaces in the path - is the path to chrome wrapped in quotation marks? If you run that command on its own, without zinigo involved, does chrome open?

**Comment by matheusmaus** [comment]
Hi @TheAxeDude,

No worries, I tried to open Google Chrome only via the path and worked, after that, I tried something else.

I didn't use the Square Brackets in the path, worked flawlessly. 

Thanks for your help.
