### ISSUE TITLE
cmd.Run() failed with exec: "C:" file does not exist

### ISSUE THREAD

**Issue by hezhong2124** [TheAxeDude/ZiniGo#15]
Chrome's path has been set correctly, and the program is running as an administrator, but an error occurred when starting to download the issue:
cmd.Run() failed with exec: "C:" file does not exist. You should retry this page.Source

**Comment by TheAxeDude** [comment]
Hi,

Can you please paste the full command that is failing? It should be printed just before the error - then we can dig in. My guess is a weird character, or a space.

**Comment by hezhong2124** [comment]
My Config.json file:
{
 "username":"Username",
 "password":"Password",
 "chromepath":"C:\Program Files\Google\Chrome\Application\chrome.exe"
}

Running the program:
Config file loaded
Username taken from config file
password taken from config file
chromepath taken from config file
Starting the application
Loading HTML template
Resolved working directory to D:\ZinoGo-master\built
Checking if issue exists: D:\ZiniGo-master\built/issue/xxxxx.pdf
Downloading issue: xxxxx
source (SVG file URL)
ID: 0
[C --headless --disable-gpu --print-to-pdf=D:\ZiniGo-master\built/issue/xxxx_1.pdf --no-margins D:\ZiniGo-master\built/issue/xxxx_1.html
cmd.Run() failed with exec: "C:": file does not exist. You should retry this page source (SVG file URL)
...
so I cannot download any SVG file, the "issue" folder is empty.

**Comment by TheAxeDude** [comment]
Can you tweak your "chromepath":

"chromepath":"C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe"

(Replace single slashes with double slashes).

**Comment by hezhong2124** [comment]
Problem solved, the program runs normally after the modification, thanks a lot

**Comment by morriscox** [comment]
I already did so.
