### ISSUE TITLE
Forward slashes instead of backslashes

### ISSUE THREAD

**Issue by turkeyphant** [TheAxeDude/ZiniGo#24]
The Windows x64 version doesn't seem to work even if you have Chrome is the same directory.

The commands it's giving don't seem to be valid on Windows filesystems and it exits with a failure.

```
[GoogleChromePortable.exe --headless --disable-gpu --print-to-pdf=D:\Downloads\Zinigo/issue/556768_98.pdf --no-margins D:\Downloads\Zinigo/issue/556768_98.html]
Source  https://cdn2.audiencemedia.com/3be76cc016a8c850661956c5f71d14c621cf6a69_207/d427614b4348298b86aa863510fedc606ec0b04d8f6c5900421bcf6ff7319801/6f61e0310b2f99ad60357765de2526e47ca04806c4e41ee4b6abf0ea2e3830ff.svg
ID:  99
[GoogleChromePortable.exe --headless --disable-gpu --print-to-pdf=D:\Downloads\Zinigo/issue/556768_99.pdf --no-margins D:\Downloads\Zinigo/issue/556768_99.html]
Removing extra pages failed with open D:\Downloads\Zinigo/issue/556768_99.pdf: The system cannot find the file specified.
.retrying after error: open D:\Downloads\Zinigo/issue/556768_99.pdf: The system cannot find the file specified.
Terminating the application...
```

**Comment by OnoBeachBum** [comment]
I am seeing the same issue. I tried both the x64 and x86 versions. Also tried it on both Windows 10 and 11. All have the same issue.

**Comment by zeppelinguy82** [comment]
Having this same issue. Was this ever resolved?

**Comment by TheAxeDude** [comment]
Do the files get created? eg: D:\Downloads\Zinigo/issue/556768_99.pdf?

The error message to me looks like its happening in the next section. I am looking at a nicer library to form the paths, to resolve this issue.

**Comment by TheAlfreton** [comment]
Had this exact same issue - it's **resolved** by **turning every back slash in your chrome path into a forward slash**.
Download Zinigo 64, place it into a directory, then add a config JSON file to the same directory that contains the following:

{
 "username":"ZINIO USERNAME HERE",
 "password":"ZINIO PASSWORD HERE",
 "chromepath":"C:/Program Files/Google/Chrome/Application/chrome.exe"
}

When you right click on the chrome app and select 'copy as path', you'll get something that looks a little like this:
"C:\Program Files\Google\Chrome\Application\chrome.exe"
All you have to do is turn all those back slashes into forward slashes, so it looks like this instead:
"C:/Program Files/Google/Chrome/Application/chrome.exe"
