### ISSUE TITLE
Random Downloads

### ISSUE THREAD

**Issue by MeNotSoSmart** [TheAxeDude/ZiniGo#25]
Hello. Can you please tell if you happened to write up a step-by-step guide? I kind of got ZiniGo working, but it does not download the items from my Zinio downloaded magazines. I am not sure why it is downloading what it is downloading, it seems to be downloading random items. I am sure I have done something wrong, just not sure what I have done. Thank you for your help and for making this program.

Edit: ZiniGo seems to be downloading all magazines related to my account including archived.

Using Windows 10, at the command prompt in the same directory as the ZinioGo and chrome.exe (copied the chrome application folder to this location), I am executing the following:
zinigo -u=MyUser@hotmail.com -p=MyPassword [-c=/D:/Download/Zinio/chrome.exe] 

![image](https://user-images.githubusercontent.com/104449786/165361259-59647df6-7036-4a77-b9e8-25698df07dce.png)

**Comment by TheAxeDude** [comment]
Hi, that is exactly what the programs doing. 

If it detects that you've already downloaded a particular issue, it will skip it. If you want to force it to skip an issue, create a file in your issues folder with the same name as the issue.
