### ISSUE TITLE
Does this project still work?

### ISSUE THREAD

**Issue by JackJones2018** [TheAxeDude/ZiniGo#3]
Hi, 
Could you tell me if this project still works please as my download doesnt seem to be logging in,
when i run the executable on windows 10 i get the following,
'Starting the application...
Found 0 issues in library.
Loading HTML template
Terminating the application...'

google-chrome command works on its own also and loads chrome.
i changed the password to see if it gave me an error saying incorrect password but it didnt.
thanks

**Comment by TheAxeDude** [comment]
Hi,

There were a few API changes which I unfortunately haven't resolved yet (due to lack of time spent :)). I will try put time aside this week to look at the issue and update you here once done.

**Comment by Vinnie20201** [comment]
Dang, maybe I was a little late. Keep us updated please!

**Comment by JackJones2018** [comment]
Hi Guys,

Any updates on this one?
thanks

**Comment by TheAxeDude** [comment]
Hi,

Please can you try the version on the feature/testing-api-changes branch? Windows executable is here: https://github.com/TheAxeDude/ZiniGo/tree/feature/testing-api-changes/built

If you need Linux, please let me know, I dont have access to a linux env at the moment to test it, so didnt push the artifact.

**Comment by Vinnie20201** [comment]
Hello, I am a little confused on how to run the executable. Do I just run
it on the desktop? Whenever I do that nothing happens except an empty file
named "issue" appears. Cheers and thank you for your work.
