### ISSUE TITLE
Pdfs are zoomed in too close

### ISSUE THREAD

**Issue by armyofskankz** [TheAxeDude/ZiniGo#6]
I am able to run the program, get the pages, and have a full issue of a magazine created in pdf. However, each page shows only the upper left corner of the magazine page - in other words, it is zoomed in too much on the corner.

**Comment by TheAxeDude** [comment]
Hi, thanks for the feedback. Are you using the version in the master
branch, or the feature/testing-api-changes branch?

https://github.com/TheAxeDude/ZiniGo/tree/feature/testing-api-changes/built

**Comment by armyofskankz** [comment]
Testing API version

**Comment by armyofskankz** [comment]
[Games World of Puzzles - September 2020.pdf](https://github.com/TheAxeDude/ZiniGo/files/5668161/Games.World.of.Puzzles.-.September.2020.pdf)

**Comment by TheAxeDude** [comment]
Ok cool, I'll take a look and let you know!

**Comment by TheAxeDude** [comment]
Hi,

Did a quick test - it seems the "default" template is causing this. For now, please just download template.html (https://raw.githubusercontent.com/TheAxeDude/ZiniGo/feature/testing-api-changes/built/template.html) and put it in the same folder as your executable. 

I'll push a fix for this soon.

**Comment by TheAxeDude** [comment]
Hi, new version has been released (on master). Please let me know if it works

**Comment by kiloxxx** [comment]
Hi TheAxeDude, great work!

I am testing the new linux version and the zoom is still too close: any single page is horizontally cropped and vertically splitted in two pages 
[464550_19.pdf](https://github.com/TheAxeDude/ZiniGo/files/5683369/464550_19.pdf).  

There is also a minor issue, when you run the script for the first time the "issue" folder is created, but the owner has not any read and write permissions, so the script stops with an error.

**Comment by TheAxeDude** [comment]
Thanks for the feedback - admittedly, I had just hoped the linux version would work, without testing it. I will try it out asap, and let you know when it is sorted.

**Comment by BlackB846** [comment]
Hi,

I have the same issue but I found a work-around.

I download the first page and stop the further processing. I then open the generated html file and inspect the properties / source of the referenced image which will give me the exact size of the image.

I then go into the template.html file and insert the correct size in the two @page tags in pixel.

After restarting the download process, all PDFs are perfect and the final file will not have the zoomed problem anymore.

I guess the dynamic function to size the page that is embedded in the template doesn't work correctly.

**Comment by BlackB846** [comment]
One more observation - when setting the page size correctly, the PDF will show two symbols at the bottom which don't exist in the image. The PDF contains  the two characters  " and > which look like they are additional characters in the HTML file after the end of document. 

I'm not too familiar with HTML documents but if I look at the template with the injected image reference, these two exact characters follow after the </svg> tag before the </object> tag. 

I could imagine they don't belong there and they prevent the fixpage() function that is defined after the </object> tag to be executed correctly. Due to that, the size of the page is never adjusted to the size of the image which would explain the "zoomed" version with some of the files.

**Comment by BlackB846** [comment]
Hi @TheAxeDude 

I changed two minor things in the template.html which seems to solve the problem for me:

I removed the "> after the SVG_PATH place holder. You seem to insert the "> with the image reference which duplicates those two elements.

I changed the java script for fixpage which adjust the page size from:
pageCss = `@page { size: \${renderBlockInfo.width} \${fixHeight} ; margin:0;}`
to:
pageCss = "@page { size: " + renderBlockInfo.width + " " + fixHeight +" ; margin:0;}"

The variables don't seem to be replaced and therefore the page size setting is not adjusted.

**Comment by kiloxxx** [comment]
Hi, 
the change to template.html suggested by @BlackB846 worked for me, now the zoom level is correct!

> I changed the java script for fixpage which adjust the page size from:
> pageCss = @page { size: \${renderBlockInfo.width} \${fixHeight} ; margin:0;}
> to:
> pageCss = "@page { size: " + renderBlockInfo.width + " " + fixHeight +" ; margin:0;}"

**Comment by TheAxeDude** [comment]
Thanks a lot for experimenting with this, @BlackB846  & @kiloxxx ! I'll add the changes you suggested to the default template file.

**Comment by BlackB846** [comment]
All of my magazines work with the modified template.

**Comment by armyofskankz** [comment]
The latest version worked for me without issues. Thanks
