### ISSUE TITLE
10 issue limitation?

### ISSUE THREAD

**Issue by dzavelson** [TheAxeDude/ZiniGo#8]
I was able to download for 10 issues in my library, but then the app stops.   My Zinio library probably has close to 100 issues, so I'm not sure why its stopping at 10.  When the app runs it says "Found 10 issues in library."   I also tried to "archive" within Zinio all of the newest issues that were already downloaded to see if it might then catch the next 10 most recent.   But it still only sees 10 and says those issues were already downloaded and found.

**Comment by TheAxeDude** [comment]
Hi,

I dont have 10 issues yet, so haven't encountered the issue. I will do some digging.

**Comment by dzavelson** [comment]
Sounds good.   Happy to help troubleshoot if you want to check using my larger library.

**Comment by mugurelu** [comment]
When you fetch the list of issues in GetLibrary, you need to append ?limit=XXX on the link, to fetch a bigger chunk. This issue probably manifests only on big libraries.

Not sure of there's a maximum number, I tried with 240 in my case and it got the entire library.

**Comment by TheAxeDude** [comment]
Aha!

Thanks. I was waiting for my subscription to exceed 10 issues at the end of
the month.

I'll modify to go through all the items asap. Thanks for the help!

**Comment by TheAxeDude** [comment]
@mugurelu Can you confirm that passing limit=0 returns all of your issues? Might be an easier way than paginating. On my library it still returns all issues.

**Comment by mugurelu** [comment]
@TheAxeDude just tested now, limit=0 gets only the most recent 10 issues.

**Comment by TheAxeDude** [comment]
Ah, thanks for trying. I will work on going the paginated route then :-)

**Comment by TheAxeDude** [comment]
Have put in a quickfix for the issue, on https://github.com/TheAxeDude/ZiniGo/tree/master/built.

It will fetch issues in batches of 120 (same as the website) until none are returned.

**Comment by dzavelson** [comment]
Thanks!  Seems to be working for me now.   Up to 19 issues now and still going.

**Comment by TheAxeDude** [comment]
Success! Glad it's working.
