### ISSUE TITLE
Filtering out invalid characters in title names

### ISSUE THREAD

**Issue by dzavelson** [TheAxeDude/ZiniGo#9]
I came across a problem where a magazine issue title has an invalid windows character in it.   In my case there is  a title that was named for 2 months, for example:  "Road & Track - Mar/Apr 2018."   So zinigo sees that name isn't in my folder (which it can never be since it has invalid characters for windows) and it starts to download.   Once it has all of the individual pages, it goes to consolidate but it can't write the filename since it would have an invalid character.   I would actually be ok with this as I can manually regroup, but the problem is  that every time I re-start zinigo it will see that title is  not present and download it all over again.  

For other issues, I've been able to put in dummy names to get it to skip over issues I don't want, but since the title has invalid characters we can never fake that in the folder.

**Comment by TheAxeDude** [comment]
Thanks for the feedback!

I've added a simple filter for the characters generally not allowed in windows (They'll be replaced with _ so that its clear there was something replaced).

Please let me know if it works or causes issues...All my issues have very plain titles.

**Comment by dzavelson** [comment]
That appears to have done it.  Many thanks!
